project:
  type: book
  output-dir: docs



book:
  title: "Introduction to `pyspark`"
  author: "Pedro Duarte Faria"
  date: "today"
  navbar: 
    background: "#164e80"
    left: 
      - text: "Visit the author's blog"
        href: "https://pedro-faria.netlify.app/"
    right: 
      - icon: github
        href: "https://github.com/pedropark99/Introd-pyspark"
  edition: "First edition"
  cover-image: "Cover/cover1.png"
  chapters:
    - index.qmd
    - Chapters/02-python.qmd
    - Chapters/03-spark.qmd
    - Chapters/04-dataframes.qmd
    - Chapters/04-columns.qmd
    - Chapters/05-transforming.qmd
    - Chapters/07-import.qmd
    - Chapters/06-dataframes-sql.qmd
    - Chapters/08-transforming2.qmd
    - Chapters/09-strings.qmd
    - Chapters/10-datetime.qmd
    - Chapters/references.qmd

bibliography: references.bib
number-sections: true
format:
  html:
    theme: 
      - cosmo
      - theme.scss
  # pdf:
  #   mainfont: Times New Roman
  #   monofont: Inconsolata
  #   fontsize: 11pt
  #   keep-tex: false
